### ISSUE TITLE
转onnx遇到点问题

### ISSUE THREAD

**Issue by shenjun1994** [Hanson0910/MNNSuperGlue#10]
您好，请问一下，用原作者的代码转onnx的时候遇到点问题，grid_sample等一些算子不支持，不知道您在转换onnx的时候作了哪些修改？

**Comment by Hanson0910** [comment]
> 您好，请问一下，用原作者的代码转onnx的时候遇到点问题，grid_sample等一些算子不支持，不知道您在转换onnx的时候作了哪些修改？

我自己用C++重写了grid_sample,参考src/common.cpp

**Comment by shenjun1994** [comment]
好的，谢谢，您在转onnx的时候还修改了别的吗，可以上传这部分代码参考对比一下吗？

**Comment by lvyong1943** [comment]
> 您好，请问一下，用原作者的代码转onnx的时候遇到点问题，grid_sample等一些算子不支持，不知道您在转换onnx的时候作了哪些修改？

您好，请问您解决那个转onnx的问题了么，我转onnx也遇到这个问题了？

**Comment by Hanson0910** [comment]
> > 您好，请问一下，用原作者的代码转onnx的时候遇到点问题，grid_sample等一些算子不支持，不知道您在转换onnx的时候作了哪些修改？
> 
> 您好，请问您解决那个转onnx的问题了么，我转onnx也遇到这个问题了？

grid_
